### ISSUE TITLE
No browse or capture image code in home.ts file as in article

### ISSUE THREAD

**Issue by developercakephp** [amuramoto/ionic-imagepicker-sample#1]
http://blog.ionic.io/ionic-native-accessing-ios-photos-and-android-gallery-part-2

No browse or capture image code in home.ts file as in article
There is no code in repo for this.

**private openGallery (): void {
  let options = {
    maximumImagesCount: 8,
    width: 500,
    height: 500,
    quality: 75
  }

  ImagePicker.getPictures(options).then(
    file_uris => this._navCtrl.push(GalleryPage, {images: file_uris}),
    err => console.log('uh oh')
  );
}**

**Comment by amuramoto** [comment]
Perhaps you are looking at the wrong branch? That code is in master:

https://github.com/amuramoto/ionic-imagepicker-sample/blob/master/app/pages/home/home.ts
